### ISSUE TITLE
Hey I can't seem to find the complete consensus of gamemodes that exist, what are they?

### ISSUE THREAD

**Issue by MountainLabz** [landfallgames/tabg-word-list#23]
The only gamemodes I can get to work are Normal and Brawl.
Google and the TABG fandom wiki (https://totally-accurate-wikigrounds.fandom.com/wiki/Restricted_Game_Modes) says that there are like 15 gamemodes

No big deal i'm just curious about it.

**Comment by SuperAgentAlex** [comment]
restricted gamemodes are NOT the same as battleroyale, bomb, etc.

**Comment by MountainLabz** [comment]
Ahhh sorry.
